AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  resumeChallenge
  Sample SAM Template for resumeChallenge

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: fayeez-resume-table
  Api:
    TracingEnabled: True

Resources:
  FayeezResumeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTable
      Events:
        FayeezResume:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Auth:
              Authorizer: null
            Path: /hit
            Method: post
            RequestParameters:
              - method.request.header.Access-Control-Allow-Origin

  MyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: MyPrimaryKey
        Type: String
      TableName: fayeez-resume-table

  FrontEndBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fayeez-resume-challenge-bucket
      AccessControl: PublicRead
      MetricsConfigurations:
        - Id: EntireBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
        RoutingRules:
          - RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: '404'
              KeyPrefixEquals: out1/
            RedirectRule:
              HostName: fayeezresumechallenge.com
              ReplaceKeyPrefixWith: report-404/
    DeletionPolicy: Retain


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FayeezResumeApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FayeezResumeFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt FayeezResumeFunction.Arn
  FayeezResumeFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FayeezResumeFunctionRole.Arn
  WebsiteURL:
    Value: !GetAtt FrontEndBucket.WebsiteURL
    Description: URL for website hosted on S3
  FayeezResumeChallengeBucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt FrontEndBucket.DomainName
    Description: Name of S3 bucket to hold website content
